---
- name: Deploy Docker application
  hosts: docker 
  become: yes

  roles:
    - github_app
    - docker

- name: Deply Docker compose
  hosts: docker-compose 
  become: yes

  roles:
    - github_app
    - docker-compose