---
- name: Install git
  dnf:
    name: git
    state: present

- name: Create a directory
  file:
     path: /opt/app 
     state: directory  
     mode: '0755'  

- name: Clone the repository 
  git:
    repo: 'https://github.com/dm-alekseev/alpine.git'  
    dest: /opt/app
    version: main  

#- name: Start the application (if applicable)
#  command: /path/to/destination/start.sh  # Замените на команду запуска приложения, если требуется

